upgrade to new model kit, finish sdk
feather-modules/feather-user-module pull request #17
Opened 2024-04-29 12:04 UTC by GErP83

2024-04-29 13:31 UTC, tib approved these changes

2024-04-29 14:11 UTC, mzpx requested changes

2024-04-29 14:11 UTC, mzpx commented on Sources/UserModule/Adapters/PushToken+Adapters.swift
> +extension User.PushToken.Create: CreateInterface {}
this inheritance should be in the PushToken+Validators.swift file

2024-04-29 14:11 UTC, mzpx commented on Sources/UserModule/Adapters/PushToken+Adapters.swift
> +extension User.PushToken.Update: UpdateInterface {}
this inheritance should be in the PushToken+Validators.swift file

2024-04-29 14:11 UTC, mzpx commented on Sources/UserModule/Adapters/PushToken+Adapters.swift
> +}
I would change this for an init function implementation to make sync with the other adapter implementations, like this:
```suggestion
extension Recipient {
   init(model: User.PushToken.Model) {
    self.init(model... etc.)
   }
}

extension [Recipient] {
    init(models: [Model]) {
        self = models.map { Recipient(model: $0) }
    }
}
```
of course after this change you need to change the lines in PushController.swift from 'recipients = tokenList.toPushRecipient()' to 'recipients = .init(models: tokenList)'

2024-04-29 14:11 UTC, mzpx commented on Sources/UserModuleKit/Interfaces/Account+Interface.swift
>      func get(
It should be renamed to "require" because of Detail return is not optional (not Detail?)

2024-04-29 14:11 UTC, mzpx commented on Sources/UserModuleKit/Interfaces/Profile+Interface.swift
>      func get() async throws -> User.Account.Detail
It should be renamed to "require" because of Detail return is not optional (not Detail?)

2024-04-29 14:11 UTC, mzpx commented on Sources/UserModuleKit/Interfaces/Role+Interface.swift
>      func get(
It should be renamed to "require" because of Detail return is not optional (not Detail?)

2024-04-29 19:11 UTC, mzpx requested changes
Sorry Gábor for my request changes :D but good news these are super small ones :D

2024-04-29 19:11 UTC, mzpx commented on Sources/UserModule/Validators/PushToken+Validators.swift
> +extension User.PushToken.Create {
Small change, but this is the right place for the inheritance :)
```suggestion
extension User.PushToken.Create: CreateInterface {
```

2024-04-29 19:11 UTC, mzpx commented on Sources/UserModule/Validators/PushToken+Validators.swift
> +extension User.PushToken.Update {
Small change, but this is the right place for the inheritance :)
```suggestion
extension User.PushToken.Update: UpdateInterface {
```

2024-04-29 19:11 UTC, mzpx commented on Sources/UserModule/Validators/PushToken+Validators.swift
> +extension User.PushToken.Update: UpdateInterface {}
These lines are not needed.

2024-04-30 08:23 UTC, GErP83 commented
> Sorry Gábor for my request changes :D but good news these are super small ones :D

No worries :P

2024-04-30 09:12 UTC, mzpx approved these changes

2024-04-30 16:14 UTC, viaszkadi approved these changes

2024-04-30 16:27 UTC, merged